export enum ContentType {
    JSON = 'application/json',
    XML = 'application/xml',
    HTML = 'text/html',
    PLAIN_TEXT = 'text/plain',
    CSS = 'text/css',
    CSV = 'text/csv',
    JAVASCRIPT = 'application/javascript',
    FORM_URLENCODED = 'application/x-www-form-urlencoded',
    FORM_DATA = 'multipart/form-data',
    OCTET_STREAM = 'application/octet-stream',
    PDF = 'application/pdf',
    ZIP = 'application/zip',
    PNG = 'image/png',
    JPEG = 'image/jpeg',
    GIF = 'image/gif',
    WEBP = 'image/webp',
    SVG = 'image/svg+xml',
    MP3 = 'audio/mpeg',
    MP4 = 'video/mp4'
}
